/**
 * Render the Homebrew formula for a released version.
 *
 * Usage: bun run scripts/render-formula.ts <version> <checksums.txt> [> sendfm.rb]
 *
 * The formula is generated, never hand-edited: every field in it derives from a
 * release that already exists, so a human editing the tap directly can only
 * introduce drift. CI runs this after publishing a release and commits the
 * output to the tap repo.
 *
 * Checksums come from the release's own checksums.txt rather than being
 * recomputed here. Recomputing would mean re-downloading the assets and would
 * silently "succeed" against whatever bytes came back — the point of a checksum
 * is that it was produced next to the bytes that were uploaded.
 *
 * The component order (desc, homepage, license), the hyphenated
 * "command-line" in the desc, and `url :stable` in the livecheck are all
 * required by `brew style` — it rejects the more obvious spellings of each.
 * That check runs in the tap, not here, so this comment is the only warning a
 * future edit gets.
 *
 * Homebrew is macOS + Linux only, so the windows-x64.zip asset is deliberately
 * unused. Four platforms must be present; a missing one is a hard error rather
 * than a formula that omits a platform and fails at `brew install` time on
 * whichever machine happens to hit it.
 */

const PLATFORMS = [
    { asset: 'darwin-arm64', os: 'macos', cpu: 'arm' },
    { asset: 'darwin-x64', os: 'macos', cpu: 'intel' },
    { asset: 'linux-arm64', os: 'linux', cpu: 'arm' },
    { asset: 'linux-x64', os: 'linux', cpu: 'intel' },
] as const;

const REPO = 'slingshot/bolter';

const [, , versionArg, checksumsPath] = process.argv;

if (!versionArg || !checksumsPath) {
    console.error('usage: render-formula.ts <version> <checksums.txt>');
    process.exit(1);
}

// Accept `v0.1.0` or `0.1.0`; the tag carries the v, the formula never does.
const version = versionArg.replace(/^v/, '');
if (!/^\d+\.\d+\.\d+$/.test(version)) {
    console.error(`refusing version '${versionArg}': expected X.Y.Z`);
    process.exit(1);
}

const checksums = new Map<string, string>();
for (const line of (await Bun.file(checksumsPath).text()).split('\n')) {
    // Same `<hash>  <name>` shape install.sh and update.ts parse.
    const [hash, name] = line.trim().split(/\s+/);
    if (hash && name) {
        checksums.set(name, hash);
    }
}

const blocks = new Map<string, string[]>();
for (const { asset, os, cpu } of PLATFORMS) {
    const file = `sendfm-${version}-${asset}.tar.gz`;
    const sha = checksums.get(file);
    if (!sha) {
        console.error(`no checksum for ${file} in ${checksumsPath}`);
        process.exit(1);
    }
    const lines = blocks.get(os) ?? [];
    lines.push(
        `    on_${cpu} do`,
        `      url "https://github.com/${REPO}/releases/download/v${version}/sendfm-${version}-${asset}.tar.gz"`,
        `      sha256 "${sha}"`,
        '    end',
    );
    blocks.set(os, lines);
}

// The version is written literally into each url and NOT declared as a
// `version` stanza: Homebrew scans it back out of the url, and declaring both
// fails `brew audit --strict` as redundant. `version` is still available to the
// test block from that scan. Every url is emitted from the same `version`
// constant here, so a bump cannot leave one platform on the previous release.
const formula = `# typed: false
# frozen_string_literal: true

# This file is generated by apps/cli/scripts/render-formula.ts in
# slingshot/bolter and overwritten on every release. Edits here are lost.
class Sendfm < Formula
  desc "Send and receive end-to-end encrypted files from the command-line"
  homepage "https://send.fm"
  license "MPL-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
${blocks.get('macos')?.join('\n')}
  end

  on_linux do
${blocks.get('linux')?.join('\n')}
  end

  def install
    bin.install "sendfm"
    # Runs \`sendfm completions <shell>\` during install and captures stdout.
    # Only correct from v0.1.1: v0.1.0 named the script after \`process.cwd()\`,
    # so this would have installed a completion bound to whichever directory
    # the build ran in. The generator that did that is gone — the name now
    # comes from the CLI's own definition and nothing reads the filesystem.
    generate_completions_from_executable(bin/"sendfm", "completions", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sendfm --version")
  end
end
`;

process.stdout.write(formula);

// This file is a script, not a library, but top-level `await` is only allowed
// in a module — and with no imports or exports TypeScript classifies it as a
// global script. An empty export is what makes it a module.
export {};
